[package]
name = "c05"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
thiserror = "2"
dep-01 = "1"
dep-02 = "1"
dep-03 = "1"
dep-04 = "1"
dep-05 = "1"
dep-06 = "1"
dep-07 = "1"
dep-08 = "1"
dep-09 = "1"
dep-10 = "1"
dep-11 = "1"
dep-12 = "1"
dep-13 = "1"
dep-14 = "1"
dep-15 = "1"
dep-16 = "1"
dep-17 = "1"
dep-18 = "1"
dep-19 = "1"
dep-20 = "1"
dep-21 = "1"
dep-22 = "1"
dep-23 = "1"
dep-24 = "1"
dep-25 = "1"
dep-26 = "1"
dep-27 = "1"
dep-28 = "1"
dep-29 = "1"
anyhow = "1"
dep-30 = "1"
dep-31 = "1"
dep-32 = "1"
dep-33 = "1"
dep-34 = "1"
dep-35 = "1"
dep-36 = "1"
dep-37 = "1"
dep-38 = "1"
dep-39 = "1"
dep-40 = "1"
dep-41 = "1"
dep-42 = "1"
dep-43 = "1"
dep-44 = "1"
